### ISSUE TITLE
MD_S8ChopWhitespace does not chop newlines

### ISSUE THREAD

**Issue by bvisness** [Dion-Systems/metadesk#10]
`MD_S8ChopWhitespace` does not chop newlines off the end of a string, because it checks using `MD_CharIsSpace`, which does not include newlines, because newlines are handled differently within the parser.

This is weird and counterintuitive, since newlines are obviously whitespace. I think the root of the problem is that `MD_CharIsSpace` probably should recognize newlines as well, but currently cannot do so because newlines are special.

My suggestion would be to keep `MD_CharIsSpace`, but have it use a more conventional notion of whitespace (probably just anything recognized by [`isspace`](https://www.cplusplus.com/reference/cctype/isspace/)?) Any parser code can simply use other internal functions that are not part of the public API.

**Comment by ryanfleury** [comment]
This was fixed on `dev`, forgot to merge it over until now. Thanks for the heads up!
