### ISSUE TITLE
Discrepancy between MD_WIN32_Reserve and MD_LINUX_Reserve return value on failure

### ISSUE THREAD

**Issue by catsanddo** [Dion-Systems/metadesk#15]
On Windows, `VirtualAlloc` always returns a `NULL` pointer on failure. According to the `mmap(2)` from the linux man pages, `mmap` actually returns `MAP_FAILED` on failure which is defined as `(void *) -1`.

This means that there is actually a pretty big discrepancy between their failure values. It doesn't actually cause any issues in the code because in either case any failure is caught by the commit call on line [461](https://github.com/Dion-Systems/metadesk/blob/master/source/md.c#L461). Probably worth fixing though because it could cause a big surprise in the future.

**Comment by ryanfleury** [comment]
Thanks for the heads up. Fixed.
