### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by aidan-h** [Dion-Systems/metadesk#25]
What happened to Dion Systems and Metadesk? The website isn't up anymore. I want to pick up where you all left off, so where can I find relevant resources for doing so?

**Comment by rlabrecque** [comment]
Ryan at least works for Epic currently, and they have a pretty strict policy against non-work projects.

**Comment by ryanfleury** [comment]
That is not why Dion has been retired; I won't get into it on here. Metadesk lives on as a useful textual format which is used throughout both my work & personal projects, though I no longer use the library. It is still usable, though.
