### ISSUE TITLE
Errors in the API reference

### ISSUE THREAD

**Issue by bvisness** [Dion-Systems/metadesk#8]
I've been using the official reference to generate some Metadesk bindings for another language, and I've found a few issues through that process:

- `MD_PushNewReference` is missing the `arena` parameter.
- `arg_string` in `MD_TagArgFromString` is listed as type `int`, when it should be `MD_String8`.
- `MD_MakeDetachedError` is listed in the reference, but does not exist at all in the source.
- The reference lists a `string_hash` field on `MD_Node` that does not exist in the source.

(I'm sure this is not exhaustive, but this is what I've found so far.)

**Comment by ryanfleury** [comment]
Fixed, thanks!
